name: Update Jira Issue on PUSH

on:
  push:
    branches:
      - develop

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue Key
        id: extract
        run: |
          echo "JIRA_KEY=$(git log -1 --pretty=%B | grep -o '[A-Z]\+-[0-9]\+')" >> $GITHUB_OUTPUT

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Transition Jira issue to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract.outputs.JIRA_KEY }}
          transition: Done
